### PR TITLE
Basic support for text attributes/colors.

### PR DESCRIPTION
**Pull request by MatthewBennington**
I wanted to make text certain colors, so I did this:

- Added a `start_color` method to Crt. This enables text coloring, it must be called before any colors can be used. I chose not to make it run by default, because it overwrites the terminals default colors, which may be desired.
- Added a `Color` enum to Crt to make selecting colors easy.
- Added the `ColorPair` class. This is an OOP approach to ncurses' `COLOR_PAIR(int)` & `init_pair(short, int, int)` functions.
- Added `init_color` method to Crt. This changes a color's value.
- Added `attribute_on`, `attribute_off` and `attribute_set` methods to window, in order to change text/window colors. All of these methods take a color pair, `attribute_on` and `attribute_off` can also take a member of the `Attribute` enum.
- Added an attribute enum. 
- Finally, added example usage of color methods.

### CODE REVIEW

**Comment by maiha** [comment]
Great!
> Finally, added example usage of color methods.

Missing? I'd like to try the example!

**Comment by MatthewBennington** [comment]
Shoot, I'm not sure how that ended up not getting committed. Well, I borked my local repo pretty soon after making this request, so I'll rewrite it.

**Comment by MatthewBennington** [comment]
Pushed example usage, and a simple spec file for it.

**Comment by maiha** [comment]
Thank you @MatthewBennington !
And thank you for the spec as well!

**Pull request merged**
